#!/usr/bin/env python3
"""
Demo: Hugging Face Synthetic Data Generation
Shows how to use the HuggingFace method to generate free synthetic translation data
"""

print("="*70)
print("🤗 DEMO: Generación de Datos Sintéticos con Hugging Face")
print("="*70)
print()
print("Este demo muestra cómo usar Hugging Face GRATIS para generar datos")
print("sintéticos para entrenar tu modelo de traducción.")
print()
print("VENTAJAS:")
print("  ✅ 100% GRATUITO - Sin tarjeta de crédito")
print("  ✅ Alta calidad - Modelos de última generación")
print("  ✅ Múltiples modelos - FLAN-T5, Mistral, BLOOM, GPT-2")
print("  ✅ Sin instalación local - Solo internet")
print()
print("="*70)
print()

# Step 1: Explain token
print("PASO 1: Obtener Token Gratuito (Opcional pero Recomendado)")
print("-"*70)
print()
print("Para obtener más límites (GRATIS):")
print("  1. Ir a: https://huggingface.co/join")
print("  2. Crear cuenta (sin tarjeta)")
print("  3. Obtener token: https://huggingface.co/settings/tokens")
print("  4. Exportar: export HUGGINGFACE_TOKEN=tu_token")
print()
print("Sin token: ~30 requests/hora")
print("Con token: ~1000 requests/hora (¡GRATIS!)")
print()

# Step 2: Show usage examples
print("PASO 2: Generar Datos Sintéticos")
print("-"*70)
print()

print("Opción A - Uso Básico (sin token):")
print("-"*35)
print("  python scripts/generate_synthetic_data_free.py -n 100 -m huggingface")
print()

print("Opción B - Con Token (recomendado):")
print("-"*35)
print("  python scripts/generate_synthetic_data_free.py -n 1000 -m huggingface --hf-token TU_TOKEN")
print()

print("Opción C - Con Modelo Específico:")
print("-"*35)
print("  # FLAN-T5-XL (mejor calidad)")
print("  python scripts/generate_synthetic_data_free.py -n 500 -m huggingface --hf-text-model flan-t5-xl")
print()
print("  # Mistral (última generación)")
print("  python scripts/generate_synthetic_data_free.py -n 500 -m huggingface --hf-text-model mistral")
print()
print("  # BLOOM (multilingüe)")
print("  python scripts/generate_synthetic_data_free.py -n 500 -m huggingface --hf-text-model bloom")
print()

# Step 3: Models comparison
print("PASO 3: Elegir el Modelo Correcto")
print("-"*70)
print()
print("Modelos disponibles:")
print()
print("  1. flan-t5 (default)")
print("     → Velocidad: ⭐⭐⭐⭐")
print("     → Calidad: ⭐⭐⭐⭐")
print("     → Recomendado: Equilibrio perfecto")
print()
print("  2. flan-t5-xl")
print("     → Velocidad: ⭐⭐⭐")
print("     → Calidad: ⭐⭐⭐⭐⭐")
print("     → Recomendado: Máxima calidad")
print()
print("  3. mistral")
print("     → Velocidad: ⭐⭐⭐")
print("     → Calidad: ⭐⭐⭐⭐⭐")
print("     → Recomendado: Última generación")
print()
print("  4. bloom")
print("     → Velocidad: ⭐⭐⭐⭐")
print("     → Calidad: ⭐⭐⭐⭐")
print("     → Recomendado: Multilingüe")
print()
print("  5. gpt2-large")
print("     → Velocidad: ⭐⭐⭐⭐⭐")
print("     → Calidad: ⭐⭐⭐⭐")
print("     → Recomendado: Velocidad")
print()

# Step 4: Best practices
print("PASO 4: Mejores Prácticas")
print("-"*70)
print()
print("Para máximos resultados:")
print()
print("  1. Obtén un token gratuito (más límites)")
print("  2. Usa lotes pequeños-medianos: -b 50")
print("  3. Empieza con 100 pares para probar")
print("  4. Luego escala a 1000-5000 pares")
print("  5. Combina con otros métodos para más datos:")
print()
print("     # Base rápida con rule-based")
print("     python scripts/generate_synthetic_data_free.py -n 5000 -m rulebased")
print()
print("     # Calidad alta con HuggingFace")
print("     python scripts/generate_synthetic_data_free.py -n 2000 -m huggingface --hf-text-model flan-t5-xl")
print()
print("     # Total: 7000 pares con buena calidad!")
print()

# Step 5: Next steps
print("PASO 5: Entrenar Tu Modelo")
print("-"*70)
print()
print("Una vez generados los datos:")
print()
print("  1. Los datos están en: synthetic_data/")
print("  2. Entrenar modelo:")
print("     python scripts/train_model_hpc.py -d synthetic_data")
print()
print("  3. Traducir PDFs:")
print("     python src/translate_pdf.py documento.pdf")
print()

print("="*70)
print("📖 DOCUMENTACIÓN COMPLETA")
print("="*70)
print()
print("  • Guía completa HuggingFace: docs/HUGGINGFACE_GUIDE.md")
print("  • Todos los métodos gratis: docs/SYNTHETIC_DATA_FREE.md")
print("  • README principal: README.md")
print()
print("="*70)
print("🚀 ¡LISTO PARA EMPEZAR!")
print("="*70)
print()
print("Ejecuta cualquiera de los comandos mostrados arriba para")
print("comenzar a generar tus datos sintéticos GRATIS con Hugging Face.")
print()
print("¡Sin costos, sin límites de tiempo, sin tarjeta requerida!")
print()
print("="*70)
